@server=https://davidcaldas934-shiny-xylophone-jxwww9p7qqwfpq7w-8080.preview.app.github.dev
###
GET {{server}}/
###
GET {{server}}/cursos
###
GET {{server}}/cursos/102
###
GET {{server}}/cursos?size=3&page=0
###
GET {{server}}/cursos?sort=nombre,asc
###
GET {{server}}/cursos?sort=creditos,desc
###
POST {{server}}/cursos
Content-Type: application/json

{
    "nombre":"Contabilidad y entornos aplicativos", "creditos": 8
}
###
DELETE {{server}}/cursos/54
###
PATCH {{server}}/cursos/102
Content-Type: application/json

{
    "nombre":"Base de datos SQL", "creditos": 19
}
###
GET {{server}}/profile/cursos
###
GET {{server}}/cursos/search/findByNombre?nombre=Programacion2



###
GET {{server}}/carreras
###
POST {{server}}/carreras
Content-Type: application/json

{
    "nombre":"Contabilidad"
}
###
DELETE {{server}}/carreras/1
###
PATCH {{server}}/carreras/102
Content-Type: application/json

{
    "nombre":"Base de datos SQL", "creditos": 19
}
###
GET {{server}}/cursos/102/carreras
###
GET {{server}}/carreras/1/cursos
